/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/useColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/useThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/app/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/hooks/useColorScheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/hooks/useColorScheme.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/hooks/useThemeColor`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../src/app/index${`?${string}` | `#${string}` | ''}` | `/../src/hooks/useColorScheme${`?${string}` | `#${string}` | ''}` | `/../src/hooks/useColorScheme.web${`?${string}` | `#${string}` | ''}` | `/../src/hooks/useThemeColor${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/useColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/useThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
